package com.arjunsk.numbo.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig g_CONTACTSDaoConfig;

    private final G_CONTACTSDao g_CONTACTSDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        g_CONTACTSDaoConfig = daoConfigMap.get(G_CONTACTSDao.class).clone();
        g_CONTACTSDaoConfig.initIdentityScope(type);

        g_CONTACTSDao = new G_CONTACTSDao(g_CONTACTSDaoConfig, this);

        registerDao(G_CONTACTS.class, g_CONTACTSDao);
    }
    
    public void clear() {
        g_CONTACTSDaoConfig.getIdentityScope().clear();
    }

    public G_CONTACTSDao getG_CONTACTSDao() {
        return g_CONTACTSDao;
    }

}
