package com.arjunsk.numbo.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "G__CONTACTS".
 */
public class G_CONTACTS {

    private Long id;
    /** Not-null value. */
    private String displayName;
    /** Not-null value. */
    private String communication;

    public G_CONTACTS() {
    }

    public G_CONTACTS(Long id) {
        this.id = id;
    }

    public G_CONTACTS(Long id, String displayName, String communication) {
        this.id = id;
        this.displayName = displayName;
        this.communication = communication;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDisplayName() {
        return displayName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /** Not-null value. */
    public String getCommunication() {
        return communication;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCommunication(String communication) {
        this.communication = communication;
    }

}
